### ISSUE TITLE
SignIn Activity VideoView 변경

### ISSUE THREAD

**Issue by kyuwankim** [tokijh/Record#112]
SignIn Activity를 VideoView 로 변경하여 동적인(아름다운 여성분이 있는 그영상으로)
~아름다움을나타내고싶습니다~

**Comment by tokijh** [comment]
아앀ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by kyuwankim** [comment]
@tokijh 좀더진지하게쓸까
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by tokijh** [comment]
아뇨 맘에 드네요 ㅋㅋㅋㅋ 이게 진정한 프리죠 ㅋㅋㅋ

**Comment by kyuwankim** [comment]
@tokijh 오빠 나 밤샜는데 진척된게 하나도없엌ㅋㅋㅋㅋㅋㅋ큐ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

**Comment by kyuwankim** [comment]
04-14 07:14:10.898 30335-30335/com.team3.fastcampus.record E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.team3.fastcampus.record, PID: 30335
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.team3.fastcampus.record/com.team3.fastcampus.record.Account.SigninActivity}: java.lang.ClassCastException: android.widget.VideoView cannot be cast to android.view.ViewGroup
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2202)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2252)
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:139)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:136)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                                              Caused by: java.lang.ClassCastException: android.widget.VideoView cannot be cast to android.view.ViewGroup
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                                 at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                 at com.team3.fastcampus.record.Account.SigninActivity.onCreate(SigninActivity.java:79)
                                                                                 at android.app.Activity.performCreate(Activity.java:5275)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2166)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2252) 
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:136) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606) 
                                                                                 at dalvik.system.NativeStart.main(Native Method) 
04-14 07:15:23.900 30335-30335/? I/Process: Sending signal. PID: 30335 SIG: 9


무슨오류일까도대체
검색하면 리빌드하거나 클린하면 된다던데 뭔가 내가 xml자체를 잘못한걸까

**Comment by tokijh** [comment]
@kyuwankim push 되어있어요?

**Comment by tokijh** [comment]
영상이 어지러워 내용이 취소되었습니다.
