### ISSUE TITLE
OS(4.4)Kitkat에서 로그인, 회원가입이 되지 않음

### ISSUE THREAD

**Issue by tokijh** [tokijh/Record#93]
`E/SigninActivity: signin - NetworkController - excute - onError : null`

**Comment by tokijh** [comment]
# 문제사항
NetworkController에서 API20미만인 경우 Response.body().string()을 mainTherad에서 실행하면 Exception (아래 참고)
```
android.os.NetworkOnMainThreadException
04-11 03:09:17.303 8896-8896/com.team3.fastcampus.record W/System.err:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1166)
04-11 03:09:17.303 8896-8896/com.team3.fastcampus.record W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:682)
04-11 03:09:17.303 8896-8896/com.team3.fastcampus.record W/System.err:     at okio.Okio$2.read(Okio.java:138)
04-11 03:09:17.308 8896-8896/com.team3.fastcampus.record W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
04-11 03:09:17.308 8896-8896/com.team3.fastcampus.record W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
04-11 03:09:17.308 8896-8896/com.team3.fastcampus.record W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
04-11 03:09:17.308 8896-8896/com.team3.fastcampus.record W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
04-11 03:09:17.308 8896-8896/com.team3.fastcampus.record W/System.err:     at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:441)
04-11 03:09:17.308 8896-8896/com.team3.fastcampus.record W/System.err:     at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:425)
04-11 03:09:17.308 8896-8896/com.team3.fastcampus.record W/System.err:     at okhttp3.internal.Util.skipAll(Util.java:165)
04-11 03:09:17.313 8896-8896/com.team3.fastcampus.record W/System.err:     at okhttp3.internal.Util.discard(Util.java:147)
04-11 03:09:17.313 8896-8896/com.team3.fastcampus.record W/System.err:     at okhttp3.internal.http1.Http1Codec$ChunkedSource.close(Http1Codec.java:462)
04-11 03:09:17.313 8896-8896/com.team3.fastcampus.record W/System.err:     at okio.RealBufferedSource.close(RealBufferedSource.java:434)
04-11 03:09:17.313 8896-8896/com.team3.fastcampus.record W/System.err:     at okio.RealBufferedSource.close(RealBufferedSource.java:434)
04-11 03:09:17.313 8896-8896/com.team3.fastcampus.record W/System.err:     at okio.InflaterSource.close(InflaterSource.java:126)
04-11 03:09:17.313 8896-8896/com.team3.fastcampus.record W/System.err:     at okio.GzipSource.close(GzipSource.java:182)
04-11 03:09:17.313 8896-8896/com.team3.fastcampus.record W/System.err:     at okio.RealBufferedSource.close(RealBufferedSource.java:434)
04-11 03:09:17.313 8896-8896/com.team3.fastcampus.record W/System.err:     at okhttp3.internal.Util.closeQuietly(Util.java:100)
04-11 03:09:17.313 8896-8896/com.team3.fastcampus.record W/System.err:     at okhttp3.ResponseBody.string(ResponseBody.java:176)
04-11 03:09:17.313 8896-8896/com.team3.fastcampus.record W/System.err:     at com.team3.fastcampus.record.MainActivity$1.onSuccess(MainActivity.java:64)
```

**Comment by tokijh** [comment]
@kyuwankim #97 까지 해서 해결했습니다
